import type { CreateUnitPayload } from "../types/unit.types"

export const defaultNewUnitForm: CreateUnitPayload = {
  numero: "",
  marca: "",
  modelo: "",
  anio: "",
  no_serie: "",
  imagen: "",
  fecha_asignacion_operador: "",
  id_grupo_unidades: null,
  temp_min: 0,
  temp_max: 1,
  matricula: "",
  tipo: "",
  odometro_inicial: "",
  id_operador: null,
  id_modelo_avl: null,
  fecha_instalacion: new Date().toISOString().slice(0, 10),
  imei: "",
  chip: "",
  input1: "sin uso",
  input2: "sin uso",
  input3: "sin uso",
  input4: "sin uso",
  output1: "sin uso",
  output2: "sin uso",
  output3: "sin uso",
  output4: "sin uso",
  rs232: "sin uso",
  tipo_combustible: "",
  capacidad_tanque: "",
  rendimiento_establecido: "",
  nombre_aseguradora: "",
  telefono_aseguradora: "",
  no_poliza_seguro: "",
  vigencia_poliza_seguro: new Date().toISOString().slice(0, 10),
  vigencia_verificacion_vehicular: new Date().toISOString().slice(0, 10),
}

export const inputClass =
  "h-11 w-full rounded border border-slate-300 bg-white px-3 text-sm outline-none focus:border-slate-400"